### PR TITLE
build: support aarch64

### PR DESCRIPTION
**Pull request by kecrily**
Build for aarch64 devices, like Apple SIlicon

### CODE REVIEW

**Comment by volllly** [comment]
Hey, thanks for the contribution 🤗

Can you rebase the branch to the current main branch? I fixed the issue so the build should run through then.

**Comment by volllly** [comment]
The `ring` crate does not yet build on `aarch64-pc-windows-msvc` (briansmith/ring#1614) I'll keep an eye on that and add it as a target when its ready 👌

**Comment by mjm918** [comment]
Hi 🥲 any workaround for now?

**Comment by volllly** [comment]
Hey @mjm918 I've managed to find a workaround and released [v0.9.5](https://github.com/volllly/rotz/releases/tag/v0.9.5) with the `aarch64-pc-windows-msvc` build 🎉 

The build for this target has [http template features](https://github.com/davidB/handlebars_misc_helpers#http-content) disabled as a workaround.

**Pull request merged**
